-- Production hardening for the semantic retrieval subsystem.
-- The application has not been deployed yet, so this migration intentionally
-- tightens the canonical contract instead of preserving stale index variants.

create table if not exists public.semantic_query_embedding_cache (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  model text not null check (model ~ '^[A-Za-z0-9._-]{3,128}$'),
  query_hash text not null check (query_hash ~ '^[0-9a-f]{64}$'),
  embedding extensions.vector(768) not null,
  expires_at timestamptz not null,
  last_used_at timestamptz not null default now(),
  hit_count bigint not null default 0 check (hit_count >= 0),
  created_at timestamptz not null default now(),
  unique (user_id, model, query_hash)
);

alter table public.semantic_query_embedding_cache enable row level security;
revoke all on table public.semantic_query_embedding_cache from public, anon, authenticated;

create index if not exists semantic_query_embedding_cache_expiry_idx
  on public.semantic_query_embedding_cache (user_id, expires_at);

create table if not exists public.semantic_retrieval_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  surface text not null check (surface in ('global_search', 'topic_coverage', 'indexer')),
  mode text not null check (mode in ('lexical', 'semantic', 'hybrid', 'fallback', 'indexing')),
  model text null check (model is null or model ~ '^[A-Za-z0-9._-]{3,128}$'),
  result_count integer not null default 0 check (result_count >= 0),
  lexical_only_count integer not null default 0 check (lexical_only_count >= 0),
  semantic_only_count integer not null default 0 check (semantic_only_count >= 0),
  hybrid_count integer not null default 0 check (hybrid_count >= 0),
  total_pages integer null check (total_pages is null or total_pages >= 0),
  indexed_pages integer null check (indexed_pages is null or indexed_pages >= 0),
  duration_ms integer not null check (duration_ms >= 0 and duration_ms <= 300000),
  query_embedding_cache_hit boolean null,
  fallback_reason text null check (fallback_reason is null or char_length(fallback_reason) <= 96),
  created_at timestamptz not null default now()
);

alter table public.semantic_retrieval_events enable row level security;
revoke all on table public.semantic_retrieval_events from public, anon, authenticated;

create index if not exists semantic_retrieval_events_user_created_idx
  on public.semantic_retrieval_events (user_id, created_at desc);

create or replace function public.get_cached_semantic_query_embedding(
  target_model text,
  target_query_hash text
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  result_embedding text;
begin
  if (select auth.uid()) is null or not (select public.is_authorized_user()) then
    raise exception 'Not authorized';
  end if;
  if target_model !~ '^[A-Za-z0-9._-]{3,128}$'
    or target_query_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid semantic query cache key';
  end if;

  update public.semantic_query_embedding_cache
  set last_used_at = now(),
      hit_count = hit_count + 1
  where user_id = (select auth.uid())
    and model = target_model
    and query_hash = target_query_hash
    and expires_at > now()
  returning embedding::text into result_embedding;

  return result_embedding;
end;
$$;

create or replace function public.put_cached_semantic_query_embedding(
  target_model text,
  target_query_hash text,
  embedding_text text,
  ttl_seconds integer default 604800
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not (select public.is_authorized_user()) then
    raise exception 'Not authorized';
  end if;
  if target_model !~ '^[A-Za-z0-9._-]{3,128}$'
    or target_query_hash !~ '^[0-9a-f]{64}$'
    or embedding_text is null
    or char_length(embedding_text) > 24000
    or ttl_seconds < 300
    or ttl_seconds > 2592000 then
    raise exception 'Invalid semantic query cache payload';
  end if;

  insert into public.semantic_query_embedding_cache (
    user_id, model, query_hash, embedding, expires_at, last_used_at, hit_count
  ) values (
    (select auth.uid()),
    target_model,
    target_query_hash,
    embedding_text::extensions.vector(768),
    now() + make_interval(secs => ttl_seconds),
    now(),
    0
  )
  on conflict (user_id, model, query_hash)
  do update set
    embedding = excluded.embedding,
    expires_at = excluded.expires_at,
    last_used_at = now();
end;
$$;

create or replace function public.prune_semantic_query_embedding_cache()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_count integer;
begin
  if (select auth.uid()) is null or not (select public.is_authorized_user()) then
    raise exception 'Not authorized';
  end if;

  delete from public.semantic_query_embedding_cache
  where user_id = (select auth.uid())
    and (expires_at <= now() or last_used_at < now() - interval '30 days');
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create or replace function public.record_semantic_retrieval_event(
  event_surface text,
  event_mode text,
  event_model text,
  event_result_count integer,
  event_lexical_only_count integer,
  event_semantic_only_count integer,
  event_hybrid_count integer,
  event_total_pages integer,
  event_indexed_pages integer,
  event_duration_ms integer,
  event_query_embedding_cache_hit boolean,
  event_fallback_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not (select public.is_authorized_user()) then
    raise exception 'Not authorized';
  end if;

  insert into public.semantic_retrieval_events (
    user_id,
    surface,
    mode,
    model,
    result_count,
    lexical_only_count,
    semantic_only_count,
    hybrid_count,
    total_pages,
    indexed_pages,
    duration_ms,
    query_embedding_cache_hit,
    fallback_reason
  ) values (
    (select auth.uid()),
    event_surface,
    event_mode,
    nullif(event_model, ''),
    greatest(coalesce(event_result_count, 0), 0),
    greatest(coalesce(event_lexical_only_count, 0), 0),
    greatest(coalesce(event_semantic_only_count, 0), 0),
    greatest(coalesce(event_hybrid_count, 0), 0),
    case when event_total_pages is null then null else greatest(event_total_pages, 0) end,
    case when event_indexed_pages is null then null else greatest(event_indexed_pages, 0) end,
    least(greatest(coalesce(event_duration_ms, 0), 0), 300000),
    event_query_embedding_cache_hit,
    left(nullif(event_fallback_reason, ''), 96)
  );
end;
$$;

create or replace function public.semantic_retrieval_stats(
  lookback_hours integer default 168
)
returns table (
  event_count bigint,
  semantic_only_results bigint,
  fallback_events bigint,
  average_duration_ms double precision,
  query_cache_hit_rate double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    count(*)::bigint,
    coalesce(sum(e.semantic_only_count), 0)::bigint,
    count(*) filter (where e.mode = 'fallback')::bigint,
    coalesce(avg(e.duration_ms), 0)::double precision,
    coalesce(
      avg(case when e.query_embedding_cache_hit is null then null
               when e.query_embedding_cache_hit then 1.0 else 0.0 end),
      0
    )::double precision
  from public.semantic_retrieval_events e
  where e.user_id = (select auth.uid())
    and (select public.is_authorized_user())
    and e.created_at >= now() - make_interval(hours => least(greatest(coalesce(lookback_hours, 168), 1), 2160));
$$;

-- Canonical replacement: once a page is re-embedded, stale model/hash variants
-- are useless and are removed. This keeps the index bounded before first deploy.
create or replace function public.replace_page_semantic_chunks(
  target_page_id uuid,
  target_model text,
  target_source_hash text,
  chunk_payload jsonb
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  owner_id uuid;
  current_hash text;
  payload_count integer;
  stored_count integer;
begin
  if (select auth.uid()) is null or not (select public.is_authorized_user()) then
    raise exception 'Not authorized';
  end if;
  if target_model !~ '^[A-Za-z0-9._-]{3,128}$'
    or target_source_hash !~ '^[0-9a-f]{64}$'
    or jsonb_typeof(chunk_payload) <> 'array' then
    raise exception 'Invalid semantic chunk payload';
  end if;

  payload_count := jsonb_array_length(chunk_payload);
  if payload_count < 1 or payload_count > 24 then
    raise exception 'Invalid semantic chunk count';
  end if;

  select p.user_id, public.semantic_source_hash(public.page_effective_text(p))
  into owner_id, current_hash
  from public.pages p
  where p.id = target_page_id
    and p.user_id = (select auth.uid());

  if owner_id is null then
    raise exception 'Page not found';
  end if;
  if current_hash <> target_source_hash then
    return 0;
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(chunk_payload) as item(
      chunk_index integer,
      chunk_text text,
      embedding_text text
    )
    where item.chunk_index is null
      or item.chunk_index < 0
      or item.chunk_index >= 24
      or item.chunk_text is null
      or char_length(item.chunk_text) < 1
      or char_length(item.chunk_text) > 2400
      or item.embedding_text is null
      or char_length(item.embedding_text) > 24000
  ) then
    raise exception 'Invalid semantic chunk item';
  end if;

  if (
    select count(distinct item.chunk_index)
    from jsonb_to_recordset(chunk_payload) as item(chunk_index integer)
  ) <> payload_count then
    raise exception 'Duplicate semantic chunk index';
  end if;

  delete from public.page_semantic_chunks
  where page_id = target_page_id
    and user_id = owner_id;

  insert into public.page_semantic_chunks (
    user_id,
    page_id,
    model,
    source_hash,
    chunk_index,
    chunk_text,
    embedding,
    updated_at
  )
  select
    owner_id,
    target_page_id,
    target_model,
    target_source_hash,
    item.chunk_index,
    item.chunk_text,
    item.embedding_text::extensions.vector(768),
    now()
  from jsonb_to_recordset(chunk_payload) as item(
    chunk_index integer,
    chunk_text text,
    embedding_text text
  );

  get diagnostics stored_count = row_count;
  return stored_count;
end;
$$;

create or replace function public.prune_stale_semantic_chunks(
  target_model text
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_count integer;
begin
  if (select auth.uid()) is null or not (select public.is_authorized_user()) then
    raise exception 'Not authorized';
  end if;
  if target_model !~ '^[A-Za-z0-9._-]{3,128}$' then
    raise exception 'Invalid semantic model';
  end if;

  delete from public.page_semantic_chunks c
  using public.pages p
  where c.page_id = p.id
    and c.user_id = (select auth.uid())
    and p.user_id = c.user_id
    and (
      c.model <> target_model
      or c.source_hash <> public.semantic_source_hash(public.page_effective_text(p))
      or public.page_effective_text(p) = ''
    );

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

-- Use an explicit HNSW search breadth for production retrieval. 80 is a
-- conservative recall/latency trade-off for the expected per-user corpus size.
create or replace function public.search_pages_semantic(
  query_embedding text,
  target_model text,
  notebook_filter uuid default null,
  result_limit integer default 12
)
returns table (
  page_id uuid,
  document_id uuid,
  document_title text,
  notebook_id uuid,
  notebook_name text,
  page_number integer,
  excerpt text,
  semantic_similarity double precision
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
  perform set_config('hnsw.ef_search', '80', true);

  return query
  with query_vector as (
    select query_embedding::extensions.vector(768) as value
  ),
  ranked as (
    select
      c.page_id,
      d.id as document_id,
      d.title as document_title,
      n.id as notebook_id,
      n.name as notebook_name,
      p.page_number,
      c.chunk_text as excerpt,
      greatest(
        0.0,
        least(1.0, 1.0 - (c.embedding OPERATOR(extensions.<=>) q.value))
      )::double precision as semantic_similarity,
      row_number() over (
        partition by c.page_id
        order by c.embedding OPERATOR(extensions.<=>) q.value asc, c.chunk_index asc
      ) as page_rank
    from public.page_semantic_chunks c
    join public.pages p
      on p.id = c.page_id
      and p.user_id = c.user_id
    join public.documents d
      on d.id = p.document_id
      and d.user_id = p.user_id
    left join public.notebooks n
      on n.id = d.notebook_id
      and n.user_id = d.user_id
    cross join query_vector q
    where c.user_id = (select auth.uid())
      and (select public.is_authorized_user())
      and c.model = target_model
      and c.source_hash = public.semantic_source_hash(public.page_effective_text(p))
      and (notebook_filter is null or d.notebook_id = notebook_filter)
  )
  select
    ranked.page_id,
    ranked.document_id,
    ranked.document_title,
    ranked.notebook_id,
    ranked.notebook_name,
    ranked.page_number,
    ranked.excerpt,
    ranked.semantic_similarity
  from ranked
  where ranked.page_rank = 1
  order by ranked.semantic_similarity desc, ranked.document_title asc, ranked.page_number asc
  limit least(greatest(coalesce(result_limit, 12), 1), 50);
end;
$$;

revoke execute on function public.get_cached_semantic_query_embedding(text, text) from public, anon;
revoke execute on function public.put_cached_semantic_query_embedding(text, text, text, integer) from public, anon;
revoke execute on function public.prune_semantic_query_embedding_cache() from public, anon;
revoke execute on function public.record_semantic_retrieval_event(text, text, text, integer, integer, integer, integer, integer, integer, integer, boolean, text) from public, anon;
revoke execute on function public.semantic_retrieval_stats(integer) from public, anon;
revoke execute on function public.prune_stale_semantic_chunks(text) from public, anon;

grant execute on function public.get_cached_semantic_query_embedding(text, text) to authenticated;
grant execute on function public.put_cached_semantic_query_embedding(text, text, text, integer) to authenticated;
grant execute on function public.prune_semantic_query_embedding_cache() to authenticated;
grant execute on function public.record_semantic_retrieval_event(text, text, text, integer, integer, integer, integer, integer, integer, integer, boolean, text) to authenticated;
grant execute on function public.semantic_retrieval_stats(integer) to authenticated;
grant execute on function public.prune_stale_semantic_chunks(text) to authenticated;
