-- Adaptive page-level visual semantic enrichment.
-- Keeps visual vectors, operational queue state and telemetry separate from the
-- textual semantic index. All worker operations are service-role only.

create table public.page_visual_embeddings (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  page_id uuid not null,
  model text not null check (model ~ '^[A-Za-z0-9._-]{3,128}$'),
  source_hash text not null check (source_hash ~ '^[0-9a-f]{64}$'),
  routing_version text not null check (routing_version ~ '^[a-z][a-z0-9._-]{2,63}$'),
  routing_reason text not null check (routing_reason ~ '^[a-z][a-z0-9_]{1,63}$'),
  embedding extensions.vector(768) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, page_id, model),
  foreign key (page_id, user_id)
    references public.pages(id, user_id)
    on delete cascade
);

alter table public.page_visual_embeddings enable row level security;
alter table public.page_visual_embeddings force row level security;

create policy "Users can read their visual page embeddings"
  on public.page_visual_embeddings
  for select
  to authenticated
  using (
    user_id = (select auth.uid())
    and (select public.is_authorized_user())
  );

revoke all on table public.page_visual_embeddings from public, anon, authenticated;
grant select on table public.page_visual_embeddings to authenticated;
grant all on table public.page_visual_embeddings to service_role;

create index page_visual_embeddings_hnsw_idx
  on public.page_visual_embeddings
  using hnsw (embedding extensions.vector_cosine_ops);
create index page_visual_embeddings_owner_model_idx
  on public.page_visual_embeddings (user_id, model, updated_at desc);

create table public.page_visual_embedding_jobs (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  page_id uuid not null,
  document_id uuid not null,
  model text not null check (model ~ '^[A-Za-z0-9._-]{3,128}$'),
  document_kind text not null check (document_kind in ('image', 'pdf')),
  media_path text not null check (char_length(media_path) between 3 and 1024),
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png')),
  routing_version text not null check (routing_version ~ '^[a-z][a-z0-9._-]{2,63}$'),
  routing_reason text not null check (routing_reason ~ '^[a-z][a-z0-9_]{1,63}$'),
  temporary_media boolean not null default false,
  status text not null default 'queued' check (
    status in ('queued', 'processing', 'retryable', 'blocked_quota', 'ready', 'failed')
  ),
  attempt_count integer not null default 0 check (attempt_count between 0 and 100),
  retry_after timestamptz,
  safe_error_code text check (
    safe_error_code is null or safe_error_code ~ '^[a-z][a-z0-9_]{1,95}$'
  ),
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, page_id, model),
  foreign key (page_id, user_id)
    references public.pages(id, user_id)
    on delete cascade,
  foreign key (document_id, user_id)
    references public.documents(id, user_id)
    on delete cascade
);

alter table public.page_visual_embedding_jobs enable row level security;
alter table public.page_visual_embedding_jobs force row level security;
revoke all on table public.page_visual_embedding_jobs from public, anon, authenticated;
grant all on table public.page_visual_embedding_jobs to service_role;

create index page_visual_embedding_jobs_claim_idx
  on public.page_visual_embedding_jobs (model, status, retry_after, created_at)
  where status in ('queued', 'processing', 'retryable', 'blocked_quota');

create table public.semantic_visual_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation text not null check (operation in ('index', 'search_shadow', 'search_visible')),
  model text not null check (model ~ '^[A-Za-z0-9._-]{3,128}$'),
  item_count integer not null default 0 check (item_count between 0 and 10000),
  overlap_count integer not null default 0 check (overlap_count between 0 and 10000),
  bytes_total bigint not null default 0 check (bytes_total between 0 and 1073741824),
  duration_ms integer not null check (duration_ms between 0 and 300000),
  status text not null check (status ~ '^[a-z][a-z0-9_]{1,63}$'),
  routing_reason text check (routing_reason is null or routing_reason ~ '^[a-z][a-z0-9_]{1,63}$'),
  routing_version text check (routing_version is null or routing_version ~ '^[a-z][a-z0-9._-]{2,63}$'),
  created_at timestamptz not null default now()
);

alter table public.semantic_visual_events enable row level security;
alter table public.semantic_visual_events force row level security;
revoke all on table public.semantic_visual_events from public, anon, authenticated;
grant all on table public.semantic_visual_events to service_role;

create index semantic_visual_events_owner_created_idx
  on public.semantic_visual_events (user_id, created_at desc);

create or replace function public.queue_page_visual_embedding_job_as_user(
  target_user_id uuid,
  target_page_id uuid,
  target_model text,
  target_media_path text,
  target_mime_type text,
  target_routing_reason text,
  target_routing_version text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  page_row record;
  allowed_path text;
  is_temporary boolean;
  queued_id uuid;
begin
  if target_user_id is null
    or target_page_id is null
    or target_model !~ '^[A-Za-z0-9._-]{3,128}$'
    or target_media_path is null
    or char_length(target_media_path) not between 3 and 1024
    or target_mime_type not in ('image/jpeg', 'image/png')
    or target_routing_reason !~ '^[a-z][a-z0-9_]{1,63}$'
    or target_routing_version !~ '^[a-z][a-z0-9._-]{2,63}$'
  then
    raise exception using errcode = '22023', message = 'Invalid visual embedding job';
  end if;

  select
    p.id as page_id,
    p.user_id,
    p.document_id,
    p.status::text as page_status,
    p.temporary_image_path,
    d.kind::text as document_kind,
    d.storage_path
  into page_row
  from public.pages p
  join public.documents d
    on d.id = p.document_id
   and d.user_id = p.user_id
  where p.id = target_page_id
    and p.user_id = target_user_id
  for update of p;

  if not found then
    raise exception using errcode = 'P0002', message = 'Page not found';
  end if;
  if page_row.page_status not in ('ready', 'needs_review') then
    return jsonb_build_object('queued', false, 'code', 'page_not_ready');
  end if;

  if page_row.temporary_image_path is not null
     and page_row.temporary_image_path = target_media_path then
    allowed_path := page_row.temporary_image_path;
    is_temporary := true;
  elsif page_row.document_kind = 'image'
     and page_row.storage_path = target_media_path then
    allowed_path := page_row.storage_path;
    is_temporary := false;
  else
    raise exception using errcode = '22023', message = 'Visual media path is not current';
  end if;

  insert into public.page_visual_embedding_jobs (
    user_id,
    page_id,
    document_id,
    model,
    document_kind,
    media_path,
    mime_type,
    routing_version,
    routing_reason,
    temporary_media,
    status,
    attempt_count,
    retry_after,
    safe_error_code,
    claimed_at,
    updated_at
  ) values (
    target_user_id,
    page_row.page_id,
    page_row.document_id,
    target_model,
    page_row.document_kind,
    allowed_path,
    target_mime_type,
    target_routing_version,
    target_routing_reason,
    is_temporary,
    'queued',
    0,
    null,
    null,
    null,
    now()
  )
  on conflict (user_id, page_id, model)
  do update set
    document_id = excluded.document_id,
    document_kind = excluded.document_kind,
    media_path = excluded.media_path,
    mime_type = excluded.mime_type,
    routing_version = excluded.routing_version,
    routing_reason = excluded.routing_reason,
    temporary_media = excluded.temporary_media,
    status = 'queued',
    attempt_count = case
      when public.page_visual_embedding_jobs.media_path = excluded.media_path
       and public.page_visual_embedding_jobs.mime_type = excluded.mime_type
      then public.page_visual_embedding_jobs.attempt_count
      else 0
    end,
    retry_after = null,
    safe_error_code = null,
    claimed_at = null,
    updated_at = now()
  returning id into queued_id;

  return jsonb_build_object(
    'queued', true,
    'jobId', queued_id,
    'temporaryMedia', is_temporary
  );
end;
$$;

create or replace function public.queue_page_visual_embedding_job(
  target_page_id uuid,
  target_model text,
  target_media_path text,
  target_mime_type text,
  target_routing_reason text,
  target_routing_version text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null or not public.is_authorized_user() then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;
  return public.queue_page_visual_embedding_job_as_user(
    current_user_id,
    target_page_id,
    target_model,
    target_media_path,
    target_mime_type,
    target_routing_reason,
    target_routing_version
  );
end;
$$;

create or replace function public.claim_page_visual_embedding_jobs(
  target_model text,
  result_limit integer default 4
)
returns table (
  job_id uuid,
  user_id uuid,
  page_id uuid,
  document_id uuid,
  document_kind text,
  media_path text,
  mime_type text,
  routing_version text,
  routing_reason text,
  attempt_count integer,
  temporary_media boolean
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if target_model !~ '^[A-Za-z0-9._-]{3,128}$'
    or result_limit is null
    or result_limit < 1
    or result_limit > 6 then
    raise exception using errcode = '22023', message = 'Invalid visual worker claim';
  end if;

  return query
  with candidates as (
    select j.id
    from public.page_visual_embedding_jobs j
    join public.app_users a
      on a.user_id = j.user_id
     and a.is_active = true
    where j.model = target_model
      and (
        j.status in ('queued', 'retryable', 'blocked_quota')
        or (j.status = 'processing' and j.claimed_at < now() - interval '5 minutes')
      )
      and (j.retry_after is null or j.retry_after <= now())
    order by coalesce(j.retry_after, j.created_at), j.created_at, j.id
    for update of j skip locked
    limit result_limit
  ), claimed as (
    update public.page_visual_embedding_jobs j
    set status = 'processing',
        attempt_count = least(j.attempt_count + 1, 100),
        claimed_at = now(),
        updated_at = now(),
        safe_error_code = null
    from candidates c
    where j.id = c.id
    returning j.*
  )
  select
    c.id,
    c.user_id,
    c.page_id,
    c.document_id,
    c.document_kind,
    c.media_path,
    c.mime_type,
    c.routing_version,
    c.routing_reason,
    c.attempt_count,
    c.temporary_media
  from claimed c
  order by c.claimed_at, c.id;
end;
$$;

create or replace function public.reuse_page_visual_embedding_job(
  target_job_id uuid,
  target_source_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  job public.page_visual_embedding_jobs%rowtype;
  matched boolean;
begin
  if target_job_id is null or target_source_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = '22023', message = 'Invalid visual reuse request';
  end if;

  select * into job
  from public.page_visual_embedding_jobs
  where id = target_job_id
  for update;

  if not found or job.status <> 'processing' then
    return jsonb_build_object('reused', false);
  end if;

  select exists (
    select 1
    from public.page_visual_embeddings e
    where e.user_id = job.user_id
      and e.page_id = job.page_id
      and e.model = job.model
      and e.source_hash = target_source_hash
  ) into matched;

  if not matched then
    return jsonb_build_object('reused', false);
  end if;

  update public.page_visual_embedding_jobs
  set status = 'ready',
      retry_after = null,
      safe_error_code = null,
      updated_at = now()
  where id = job.id;

  return jsonb_build_object(
    'reused', true,
    'terminal', true,
    'pageId', job.page_id,
    'userId', job.user_id,
    'mediaPath', job.media_path,
    'temporaryMedia', job.temporary_media
  );
end;
$$;

create or replace function public.complete_page_visual_embedding_job(
  target_job_id uuid,
  target_source_hash text,
  embedding_text text,
  target_bytes_total bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  job public.page_visual_embedding_jobs%rowtype;
  current_media_path text;
  current_document_path text;
  current_document_kind text;
  media_is_current boolean := false;
begin
  if target_job_id is null
    or target_source_hash !~ '^[0-9a-f]{64}$'
    or embedding_text is null
    or char_length(embedding_text) > 24000
    or target_bytes_total is null
    or target_bytes_total < 1
    or target_bytes_total > 25165824 then
    raise exception using errcode = '22023', message = 'Invalid visual embedding completion';
  end if;

  select * into job
  from public.page_visual_embedding_jobs
  where id = target_job_id
  for update;

  if not found or job.status <> 'processing' then
    return jsonb_build_object('stored', false, 'code', 'job_not_processing');
  end if;

  select p.temporary_image_path, d.storage_path, d.kind::text
    into current_media_path, current_document_path, current_document_kind
  from public.pages p
  join public.documents d
    on d.id = p.document_id
   and d.user_id = p.user_id
  where p.id = job.page_id
    and p.user_id = job.user_id
    and p.document_id = job.document_id;

  media_is_current :=
    (job.temporary_media and current_media_path = job.media_path)
    or (
      not job.temporary_media
      and current_document_kind = 'image'
      and current_document_path = job.media_path
    );

  if not coalesce(media_is_current, false) then
    update public.page_visual_embedding_jobs
    set status = 'failed',
        safe_error_code = 'visual_source_stale',
        retry_after = null,
        updated_at = now()
    where id = job.id;
    return jsonb_build_object(
      'stored', false,
      'terminal', true,
      'code', 'visual_source_stale',
      'pageId', job.page_id,
      'userId', job.user_id,
      'mediaPath', job.media_path,
      'temporaryMedia', job.temporary_media
    );
  end if;

  insert into public.page_visual_embeddings (
    user_id,
    page_id,
    model,
    source_hash,
    routing_version,
    routing_reason,
    embedding,
    updated_at
  ) values (
    job.user_id,
    job.page_id,
    job.model,
    target_source_hash,
    job.routing_version,
    job.routing_reason,
    embedding_text::extensions.vector(768),
    now()
  )
  on conflict (user_id, page_id, model)
  do update set
    source_hash = excluded.source_hash,
    routing_version = excluded.routing_version,
    routing_reason = excluded.routing_reason,
    embedding = excluded.embedding,
    updated_at = now();

  update public.page_visual_embedding_jobs
  set status = 'ready',
      retry_after = null,
      safe_error_code = null,
      updated_at = now()
  where id = job.id;

  return jsonb_build_object(
    'stored', true,
    'terminal', true,
    'pageId', job.page_id,
    'userId', job.user_id,
    'mediaPath', job.media_path,
    'temporaryMedia', job.temporary_media
  );
end;
$$;

create or replace function public.finish_page_visual_embedding_job(
  target_job_id uuid,
  terminal_status text,
  safe_error_code text,
  retry_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  job public.page_visual_embedding_jobs%rowtype;
  is_terminal boolean;
  requested_error_code text := safe_error_code;
begin
  if target_job_id is null
    or terminal_status not in ('retryable', 'blocked_quota', 'failed')
    or safe_error_code !~ '^[a-z][a-z0-9_]{1,95}$'
    or (terminal_status = 'failed' and retry_at is not null)
    or (terminal_status <> 'failed' and retry_at is null) then
    raise exception using errcode = '22023', message = 'Invalid visual job failure';
  end if;

  select * into job
  from public.page_visual_embedding_jobs
  where id = target_job_id
  for update;

  if not found then
    return jsonb_build_object('updated', false);
  end if;

  is_terminal := terminal_status = 'failed';
  update public.page_visual_embedding_jobs
  set status = terminal_status,
      safe_error_code = requested_error_code,
      retry_after = retry_at,
      updated_at = now()
  where id = job.id;

  return jsonb_build_object(
    'updated', true,
    'terminal', is_terminal,
    'pageId', job.page_id,
    'userId', job.user_id,
    'mediaPath', job.media_path,
    'temporaryMedia', job.temporary_media
  );
end;
$$;

create or replace function public.clear_page_visual_embedding_temporary_media(
  target_user_id uuid,
  target_page_id uuid,
  expected_media_path text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if target_user_id is null
    or target_page_id is null
    or expected_media_path is null
    or char_length(expected_media_path) not between 3 and 1024 then
    raise exception using errcode = '22023', message = 'Invalid visual temporary-media cleanup';
  end if;

  update public.pages
  set temporary_image_path = null,
      updated_at = now()
  where id = target_page_id
    and user_id = target_user_id
    and temporary_image_path = expected_media_path;
  return found;
end;
$$;

create or replace function public.page_visual_temporary_media_needed(
  target_page_id uuid,
  expected_media_path text
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null or not public.is_authorized_user() then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;
  if target_page_id is null
    or expected_media_path is null
    or char_length(expected_media_path) not between 3 and 1024 then
    raise exception using errcode = '22023', message = 'Invalid visual temporary-media lookup';
  end if;

  return exists (
    select 1
    from public.page_visual_embedding_jobs j
    where j.user_id = current_user_id
      and j.page_id = target_page_id
      and j.media_path = expected_media_path
      and j.temporary_media = true
      and j.status in ('queued', 'processing', 'retryable', 'blocked_quota')
  );
end;
$$;

create or replace function public.record_semantic_visual_event_as_user(
  target_user_id uuid,
  event_operation text,
  event_model text,
  event_item_count integer,
  event_overlap_count integer,
  event_bytes_total bigint,
  event_duration_ms integer,
  event_status text,
  event_routing_reason text,
  event_routing_version text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if target_user_id is null
    or event_operation not in ('index', 'search_shadow', 'search_visible')
    or event_model !~ '^[A-Za-z0-9._-]{3,128}$'
    or event_item_count is null or event_item_count not between 0 and 10000
    or event_overlap_count is null or event_overlap_count not between 0 and 10000
    or event_bytes_total is null or event_bytes_total not between 0 and 1073741824
    or event_duration_ms is null or event_duration_ms not between 0 and 300000
    or event_status !~ '^[a-z][a-z0-9_]{1,63}$'
    or (event_routing_reason is not null and event_routing_reason !~ '^[a-z][a-z0-9_]{1,63}$')
    or (event_routing_version is not null and event_routing_version !~ '^[a-z][a-z0-9._-]{2,63}$') then
    raise exception using errcode = '22023', message = 'Invalid visual semantic telemetry';
  end if;

  insert into public.semantic_visual_events (
    user_id, operation, model, item_count, overlap_count, bytes_total,
    duration_ms, status, routing_reason, routing_version
  ) values (
    target_user_id, event_operation, event_model, event_item_count, event_overlap_count,
    event_bytes_total, event_duration_ms, event_status, event_routing_reason, event_routing_version
  );
end;
$$;

create or replace function public.record_semantic_visual_event(
  event_operation text,
  event_model text,
  event_item_count integer,
  event_overlap_count integer,
  event_bytes_total bigint,
  event_duration_ms integer,
  event_status text,
  event_routing_reason text default null,
  event_routing_version text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null or not public.is_authorized_user() then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  perform public.record_semantic_visual_event_as_user(
    current_user_id,
    event_operation,
    event_model,
    event_item_count,
    event_overlap_count,
    event_bytes_total,
    event_duration_ms,
    event_status,
    event_routing_reason,
    event_routing_version
  );
end;
$$;

create or replace function public.search_pages_visual_semantic(
  query_embedding text,
  target_model text,
  notebook_filter uuid default null,
  result_limit integer default 12
)
returns table (
  page_id uuid,
  document_id uuid,
  document_title text,
  notebook_id uuid,
  notebook_name text,
  page_number integer,
  visual_similarity double precision
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not (select public.is_authorized_user()) then
    raise exception using errcode = '42501', message = 'Not authorized';
  end if;
  if target_model !~ '^[A-Za-z0-9._-]{3,128}$'
    or query_embedding is null
    or char_length(query_embedding) > 24000
    or result_limit is null
    or result_limit < 1
    or result_limit > 50 then
    raise exception using errcode = '22023', message = 'Invalid visual semantic search';
  end if;

  perform set_config('hnsw.ef_search', '80', true);

  return query
  with query_vector as (
    select query_embedding::extensions.vector(768) as value
  )
  select
    e.page_id,
    d.id,
    d.title,
    n.id,
    n.name,
    p.page_number,
    greatest(
      0.0,
      least(1.0, 1.0 - (e.embedding OPERATOR(extensions.<=>) q.value))
    )::double precision
  from public.page_visual_embeddings e
  join public.pages p
    on p.id = e.page_id
   and p.user_id = e.user_id
  join public.documents d
    on d.id = p.document_id
   and d.user_id = p.user_id
  left join public.notebooks n
    on n.id = d.notebook_id
   and n.user_id = d.user_id
  cross join query_vector q
  where e.user_id = (select auth.uid())
    and e.model = target_model
    and (notebook_filter is null or d.notebook_id = notebook_filter)
  order by e.embedding OPERATOR(extensions.<=>) q.value asc, d.title asc, p.page_number asc
  limit result_limit;
end;
$$;

create or replace function public.visual_embedding_stats(
  target_model text
)
returns table (
  indexed_pages bigint,
  pending_jobs bigint,
  failed_jobs bigint,
  latest_event_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not (select public.is_authorized_user()) then
    raise exception using errcode = '42501', message = 'Not authorized';
  end if;
  if target_model !~ '^[A-Za-z0-9._-]{3,128}$' then
    raise exception using errcode = '22023', message = 'Invalid visual embedding model';
  end if;

  return query
  select
    (select count(*) from public.page_visual_embeddings e
      where e.user_id = (select auth.uid()) and e.model = target_model)::bigint,
    (select count(*) from public.page_visual_embedding_jobs j
      where j.user_id = (select auth.uid())
        and j.model = target_model
        and j.status in ('queued', 'processing', 'retryable', 'blocked_quota'))::bigint,
    (select count(*) from public.page_visual_embedding_jobs j
      where j.user_id = (select auth.uid())
        and j.model = target_model
        and j.status = 'failed')::bigint,
    (select max(e.created_at) from public.semantic_visual_events e
      where e.user_id = (select auth.uid()) and e.model = target_model);
end;
$$;

revoke execute on function public.queue_page_visual_embedding_job_as_user(uuid, uuid, text, text, text, text, text)
  from public, anon, authenticated;
revoke execute on function public.claim_page_visual_embedding_jobs(text, integer)
  from public, anon, authenticated;
revoke execute on function public.reuse_page_visual_embedding_job(uuid, text)
  from public, anon, authenticated;
revoke execute on function public.complete_page_visual_embedding_job(uuid, text, text, bigint)
  from public, anon, authenticated;
revoke execute on function public.finish_page_visual_embedding_job(uuid, text, text, timestamptz)
  from public, anon, authenticated;
revoke execute on function public.clear_page_visual_embedding_temporary_media(uuid, uuid, text)
  from public, anon, authenticated;
revoke execute on function public.record_semantic_visual_event_as_user(uuid, text, text, integer, integer, bigint, integer, text, text, text)
  from public, anon, authenticated;

revoke execute on function public.page_visual_temporary_media_needed(uuid, text)
  from public, anon;
revoke execute on function public.record_semantic_visual_event(text, text, integer, integer, bigint, integer, text, text, text)
  from public, anon;

revoke execute on function public.queue_page_visual_embedding_job(uuid, text, text, text, text, text)
  from public, anon;
revoke execute on function public.search_pages_visual_semantic(text, text, uuid, integer)
  from public, anon;
revoke execute on function public.visual_embedding_stats(text)
  from public, anon;

grant execute on function public.queue_page_visual_embedding_job_as_user(uuid, uuid, text, text, text, text, text)
  to service_role;
grant execute on function public.claim_page_visual_embedding_jobs(text, integer)
  to service_role;
grant execute on function public.reuse_page_visual_embedding_job(uuid, text)
  to service_role;
grant execute on function public.complete_page_visual_embedding_job(uuid, text, text, bigint)
  to service_role;
grant execute on function public.finish_page_visual_embedding_job(uuid, text, text, timestamptz)
  to service_role;
grant execute on function public.clear_page_visual_embedding_temporary_media(uuid, uuid, text)
  to service_role;
grant execute on function public.record_semantic_visual_event_as_user(uuid, text, text, integer, integer, bigint, integer, text, text, text)
  to service_role;

grant execute on function public.page_visual_temporary_media_needed(uuid, text)
  to authenticated, service_role;
grant execute on function public.record_semantic_visual_event(text, text, integer, integer, bigint, integer, text, text, text)
  to authenticated;

grant execute on function public.queue_page_visual_embedding_job(uuid, text, text, text, text, text)
  to authenticated;
grant execute on function public.search_pages_visual_semantic(text, text, uuid, integer)
  to authenticated;
grant execute on function public.visual_embedding_stats(text)
  to authenticated;
